<a href="https://colab.research.google.com/github/HiNacho/courses/blob/main/Intro_to_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
import numpy as np

In [4]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
my_torch = my_torch.reshape(2,5) # Reshape the tensor 'my_torch' to a 2x5 matrix
my_torch # Display the reshaped tensor

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
mytorch2 = my_torch2.view(2,-1)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
mytorch2 = my_torch2.view(-1,5)
mytorch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
my_torch3 = torch.arange(20)

In [10]:
my_torch4 = my_torch3.reshape(2,-1) # Reshape the tensor 'my_torch3' to a 2xN matrix
my_torch4 # Display the reshaped tensor

tensor([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [11]:
my_torch3[2] = 4234 # Modify the element at index 2 of 'my_torch3'
my_torch3 # Display the modified tensor

tensor([   0,    1, 4234,    3,    4,    5,    6,    7,    8,    9,   10,   11,
          12,   13,   14,   15,   16,   17,   18,   19])

In [12]:
my_torch4 # Display the tensor my_torch4

tensor([[   0,    1, 4234,    3,    4,    5,    6,    7,    8,    9],
        [  10,   11,   12,   13,   14,   15,   16,   17,   18,   19]])

In [13]:
#Slice
my_torch_slice = my_torch4[1,5] # Select the element at row 1, column 5 of 'my_torch4'
my_torch_slice # Display the selected element

tensor(15)

In [14]:
my_torch_slices = my_torch4[1:5] # Select rows from index 1 up to (but not including) index 5 of 'my_torch4'
my_torch_slices # Display the selected rows

tensor([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [15]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [16]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [17]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

In [18]:
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [19]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [20]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [21]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

## What are Tensors?

In PyTorch, we use something called **tensors**. You can think of tensors as special containers that hold numbers.

*   A tensor can be a single number, like holding the number of apples you have (a 0-dimensional tensor or scalar).
*   It can be a list of numbers, like the scores you got on a test (a 1-dimensional tensor or vector).
*   It can be a table of numbers with rows and columns, like a spreadsheet (a 2-dimensional tensor or matrix).
*   It can even be more complex, like a box of tables (higher-dimensional tensors)!

Tensors are like the building blocks we use in PyTorch to store and work with data.

## Welcome to PyTorch Basics

PyTorch is a powerful tool used for working with numbers and data. Think of it like a special way to organize and do math with lots of numbers at once!

We use PyTorch to help computers learn and understand things, like recognizing patterns in data. It's used for various tasks in areas like artificial intelligence and machine learning.

In this notebook, we're going to learn some fundamental concepts of PyTorch by looking at some code examples.

In [22]:
import torch

# Create a tensor
original_tensor = torch.arange(12).reshape(3, 4)
print("Original tensor:")
print(original_tensor)

# Use view to create a new tensor
view_tensor = original_tensor.view(4, 3)
print("\nTensor after using view:")
print(view_tensor)

# Modify the view tensor
view_tensor[0, 0] = 99
print("\nView tensor after modification:")
print(view_tensor)
print("\nOriginal tensor after modifying view tensor:")
print(original_tensor) # Note that the original tensor is also changed

Original tensor:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Tensor after using view:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

View tensor after modification:
tensor([[99,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Original tensor after modifying view tensor:
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [23]:
import torch

# Create a tensor (re-create to demonstrate reshape behavior independently)
original_tensor_2 = torch.arange(12).reshape(3, 4)
print("Original tensor 2:")
print(original_tensor_2)

# Use reshape to create a new tensor
reshape_tensor = original_tensor_2.reshape(4, 3)
print("\nTensor after using reshape:")
print(reshape_tensor)

# Modify the reshape tensor
reshape_tensor[0, 0] = 99
print("\nReshape tensor after modification:")
print(reshape_tensor)
print("\nOriginal tensor 2 after modifying reshape tensor:")
print(original_tensor_2) # Note that the original tensor is also changed in this case, as reshape returned a view

Original tensor 2:
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

Tensor after using reshape:
tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Reshape tensor after modification:
tensor([[99,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

Original tensor 2 after modifying reshape tensor:
tensor([[99,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


# Task
Organise the code in the notebook to teach PyTorch concepts to grade 5 students, including markdown explanations and code examples for tensor creation, operations, reshape, and view.

## Introduce pytorch

### Subtask:
Add a markdown cell with a simple introduction to PyTorch, explaining what it is and what it's used for in easy-to-understand terms.


**Reasoning**:
Add a markdown cell at the beginning of the notebook with a simple introduction to PyTorch using analogies suitable for 5th graders.



In [24]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [25]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [26]:
torch.remainder(tensor_b,tensor_a)

tensor([0, 0, 1, 0])

In [27]:
torch.pow(tensor_a,tensor_b)

tensor([    1,    64,  2187, 65536])