In [1]:
import numpy as np

In [4]:
np1 = np.array([-1,-2, 1, 2, 3])
print(np1)

[-1 -2  1  2  3]


In [5]:
np.sqrt(np1)

/var/folders/tr/jb5rcznx5cx_5ggz3m54mxsm0000gn/T/ipykernel_16491/2411808288.py:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(np1)


array([       nan,        nan, 1.        , 1.41421356, 1.73205081])

In [6]:
np.absolute(np1)    


array([1, 2, 1, 2, 3])

In [7]:
np.exp(np1)

array([ 0.36787944,  0.13533528,  2.71828183,  7.3890561 , 20.08553692])

In [8]:
np.max(np1)

np.int64(3)

In [9]:
np.sign(np1)

array([-1, -1,  1,  1,  1])

In [10]:
np2 = np.arange(1, 10).reshape(3,3)
print(np2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [11]:
np4 = np.full((2,3), 7)
print(np4)

[[7 7 7]
 [7 7 7]]


In [12]:
np6 = np4[1:3]

In [13]:
np6

array([[7, 7, 7]])

## NumPy: view vs copy

This short example shows the difference between a view (a slice that shares memory with the original array) and a copy (a separate array).
We demonstrate:
- Creating a slice (view) and checking `np.shares_memory`
- Modifying the view and observing changes in the original array
- Creating a copy with `arr.copy()` and showing it does not affect the original
- `np.shares_memory` returns False for copies.

In [17]:
import numpy as np

# base array
arr = np.arange(10)
print('original arr:', arr)

# slice -> this is a view (shares memory)
view = arr[2:6]
print('view (arr[2:6]):', view)
print('shares_memory(arr, view):', np.shares_memory(arr, view))

# modify the view and show original array changes
view[0] = 999
print('After modifying view[0] = 999')
print('view:', view)
print('original arr:', arr)

# sometimes `base` points to the original (not always for copies)

original arr: [0 1 2 3 4 5 6 7 8 9]
view (arr[2:6]): [2 3 4 5]
shares_memory(arr, view): True
After modifying view[0] = 999
view: [999   3   4   5]
original arr: [  0   1 999   3   4   5   6   7   8   9]


In [18]:
# make a copy explicitly
arr = np.arange(10)
copy1 = arr[2:6].copy()    # or np.copy(arr[2:6])
copy2 = np.array(arr[2:6]) # also creates a new array
print('original arr before:', arr)
print('copy1:', copy1)
print('copy2:', copy2)
print('shares_memory(arr, copy1):', np.shares_memory(arr, copy1))

# change the copy and show original is unchanged
copy1[0] = -7
print('After modifying copy1[0] = -7')
print('copy1:', copy1)
print('original arr (unchanged):', arr)

# summary checks
print('arr[2:6].base is arr ->', arr[2:6].base is arr)
print('copy1.base is None ->', copy1.base is None)
print('np.shares_memory(arr, arr[2:6]):', np.shares_memory(arr, arr[2:6]))

original arr before: [0 1 2 3 4 5 6 7 8 9]
copy1: [2 3 4 5]
copy2: [2 3 4 5]
shares_memory(arr, copy1): False
After modifying copy1[0] = -7
copy1: [-7  3  4  5]
original arr (unchanged): [0 1 2 3 4 5 6 7 8 9]
arr[2:6].base is arr -> True
copy1.base is None -> True
np.shares_memory(arr, arr[2:6]): True


In [19]:
np5 = np.arange(10)
for i in range(len(np5)):
    np5[i] = np5[i] ** 2
print(np5)

[ 0  1  4  9 16 25 36 49 64 81]


In [20]:
array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],
                      [[7, 8, 9],
                      [10, 11, 12]]])

In [21]:
array_3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
for i in np.nditer(array_3d):
    print(i)

1
2
3
4
5
6
7
8
9
10
11
12


In [23]:
np6 = np.array([1,2,3,4,5,6,7,8,9,10])
np6

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [24]:
x = np.where(np6 % 2 == 0, np6, -1)
x

array([-1,  2, -1,  4, -1,  6, -1,  8, -1, 10])

In [25]:
y = np.where(np6 == 5)
y

(array([4]),)